### PR TITLE
(MAINT) Overall GCE Updates

### PR DESCRIPTION
**Pull request by trevor-vaughan**
* Fixed basic GCE support (did not work at all previously)
* Pinned to the working version of the API
* Added consistent timestamps to all Beaker managed resources
* Added support for RHEL and SuSE
* Added environment variable support for common GCE configuration items
* Reformatted comments for readability

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@kevpl Replaces #2 and should work without additional updates if you know the magic sauce that core beaker needs to pick the platform version vice the `image`. This is noted correctly in the new documentation in this PR and should not require additional updates to Beaker at this time but the RHEL PRs that have been put in would be a good idea for consistency across the board.

**Comment by pinkypie** [comment]
@kevpl @puppetlabs/beaker could I get another set of eyes on this please?

**Comment by trevor-vaughan** [comment]
@mchllweeks Any updates here?

**Comment by trevor-vaughan** [comment]
@pinkypie @kevpl This seems to be passing now, anything that needs to be fixed?

**Pull request merged**
